id: A45F14C95
title: 'The Great Treasure of a Hundred Blessings: A Prayer for the Long Life of Ḍākinī
  Muntso Rinpoche'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:02:39.924932
  last_modified_at: 2022-03-01 00:02:39.924945
